### ISSUE TITLE
Add New Client Response Type Value: none 

### ISSUE THREAD

**Issue by nynymike** [JanssenProject/jans#1825] opened 2022-07-19 18:07 UTC
Response Type `none` is specified in [OAuth 2.0 Multiple Response Type Encoding Practice](https://openid.net/specs/oauth-v2-multiple-response-types-1_0.html#none)

**Comment by yuriyz** [comment] 2022-11-09 20:06
It is duplicate of https://github.com/JanssenProject/jans/issues/2734
Closing it.

**Closed by yuriyz** 2022-11-09 20:06 UTC
Labels: comp-jans-auth-server, enhancement
