### ISSUE TITLE
feat: Initiating User Registration via OpenID Connect

### ISSUE THREAD

**Issue by nynymike** [JanssenProject/jans#783] opened 2022-02-08 18:02 UTC
New [draft OpenID Spec](https://openid.net/specs/openid-connect-prompt-create-1_0.html) adds another value for the `prompt` param during the authorization request:
 
```
prompt

A value of create indicates to the OpenID Provider that the client desires that the user be shown 
the account creation UX rather than the login flow. Care must be taken if combining this value 
with other prompt values. Mutually exclusive conditions can arise so it is RECOMMENDED that 
create not be combined with any other values.
```

**Comment by ossdhaval** [comment] 2023-05-10 08:36
Closing this as a duplicate of #2616

**Closed** 2023-05-10 11:48 UTC
Labels: comp-jans-auth-server
