### ISSUE TITLE
fix: fix(jans-auth-server): simple_password_auth is missed in acr_values_supported #4258 -autocreated 

### ISSUE THREAD

**Issue by mo-auto** [JanssenProject/jans#4260] opened 2023-03-22 08:31 UTC
This issue was created because no open issues were referenced in your PR (#4259).

**Comment by yuriyz** [comment] 2023-03-22 08:32
Duplicate of https://github.com/JanssenProject/jans/issues/4258

**Closed by yuriyz** 2023-03-22 08:33 UTC
Labels: kind-bug
