### ISSUE TITLE
fix(jans-cli-tui): getting error when updating IDP

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#7538] opened 2024-01-25 05:50 UTC
**Describe the bug**

**To Reproduce**
1. install jan 1.0.22
2. create idp in jans-saml
3. update newly created IDP , update name and other fields

**Expected behavior**
update IDP should be without error
and idp name should be readonly once idp get created like in KC

**Screenshots**
![image](https://github.com/JanssenProject/jans/assets/5729240/12ce5bd8-9df7-4289-8a79-e82146e45227)

**Desktop (please complete the following information):**
  - OS: suse
-jans 1.0.22
DB- opendj

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment] 2024-02-01 09:14
Duplicate of https://github.com/JanssenProject/jans/issues/7551 and closed by https://github.com/JanssenProject/jans/pull/7552

**Closed by devrimyatar** 2024-02-01 09:14 UTC
Labels: kind-bug, comp-jans-cli-tui
