### ISSUE TITLE
feat [auth-server]: Device Flow needs configurable acr

### ISSUE THREAD

**Issue by imShakil** [JanssenProject/jans#4305] opened 2023-03-25 02:48 UTC
We need a way to specify the acr (and potentially other params, like `agama_flow=...`) for device flow. Otherwise when you enable two acr's, it's unpredictable which one may run.  Perhaps we can add two Auth Server configuration JSON properties : `device_flow_default_acr` and `device_flow_extra_authn_params` ?

**Comment by yuriyz** [comment] 2023-03-25 08:32
It was already reported and fixed in 1.0.11 https://github.com/JanssenProject/jans/issues/4278

**Comment by yuriyz** [comment] 2023-03-25 08:34
Re-opening and assinging to @devrimyatar to check whether cli sets default acr correctly.

**Comment by nynymike** [comment] 2023-03-25 19:04
I repaced the original content of this message with the root cause--there is no way in Auth Server to specify the acr for device flow.

**Closed** 2023-04-03 10:32 UTC
Labels: kind-bug, kind-feature, comp-jans-tui
