### ISSUE TITLE
feat(jans-auth-server): Support `response_type` values in any order

### ISSUE THREAD

**Issue by nynymike** [JanssenProject/jans#3464] opened 2022-12-30 05:04 UTC
While this table is explicit, perhaps Auth Server should be a little more lenient: 
![image](https://user-images.githubusercontent.com/3717101/210036379-fedd4d09-618e-442c-98f6-3b9228335c59.png)

For example, the table defines `id_token token` as implicit, and as you might expect, `token id_token` returns an error. 

I don't think the order is that important.

**Comment by yuriyz** [comment] 2023-02-23 12:46
I've tested it on latest 1.0.7 and I'm not able to reproduce it. 

Sample for **response_type=id_token+token**
```
-------------------------------------------------------
REQUEST:
-------------------------------------------------------
https://jenkins-build.jans.io/jans-auth/restv1/authorize?response_type=id_token+token&client_id=a31adb60-009e-4d7c-a2cb-7d7e93a04eff&scope=openid+profile+address+email&redirect_uri=https%3A%2F%2Fjenkins-build.jans.io%2Fjans-auth-rp%2Fhome.htm&state=4a47840c-9443-47b1-8bbc-57f360ef024b&nonce=f62ffbd0-54b9-4e8f-b528-0966aaa3be8c&prompt=&ui_locales=&claims_locales=&acr_values=&request_session_id=false

-------------------------------------------------------
RESPONSE:
-------------------------------------------------------
HTTP/1.1 302 Found
Location: https://jenkins-build.jans.io/jans-auth-rp/home.htm#access_token=dced0f1b-973c-4ac5-bcb3-73708e7bc984&scope=address+openid+profile+email&id_token=eyJraWQiOiJjb25uZWN0XzQwNGU3ZWQ4LTdkNGQtNDAxNi1hNWRkLTUyM2M0NDgxMzZiMl9zaWdfcnMyNTYiLCJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJhdF9oYXNoIjoid3lhUHdJT2I3eDhMV2FzdFZFR0VBQSIsInN1YiI6IkZHV01DcWZLYlktODRfZGZoUmFtQVE3dGlwYmlqX0pCbVFiejA4UkdGaHMiLCJhbXIiOlsiMTAiXSwiaXNzIjoiaHR0cHM6Ly9qZW5raW5zLWJ1aWxkLmphbnMuaW8iLCJub25jZSI6ImY2MmZmYmQwLTU0YjktNGU4Zi1iNTI4LTA5NjZhYWEzYmU4YyIsInNpZCI6IjNjZTYxYTRkLTIzMzAtNDc1Mi1iYmE0LWJjNGViYWM0YmFhNiIsImphbnNPcGVuSURDb25uZWN0VmVyc2lvbiI6Im9wZW5pZGNvbm5lY3QtMS4wIiwiYXVkIjoiYTMxYWRiNjAtMDA5ZS00ZDdjLWEyY2ItN2Q3ZTkzYTA0ZWZmIiwicmFuZG9tIjoiNWE1ZmVkZTQtYzRlNC00NGE3LWI1ZTEtZTY0NjhjNTcxYWZiIiwiYWNyIjoiYmFzaWMiLCJzX2hhc2giOiItelZzajY0Qi1pNGhBUGsxTVNTbXRBIiwiYXV0aF90aW1lIjoxNjc2OTE2MjQ1LCJleHAiOjE2NzY5MTk4NDcsImdyYW50IjoiaW1wbGljaXQiLCJpYXQiOjE2NzY5MTYyNDd9.cFw4kAGVranaVTriRW76xXRoSs3_Z6Mf9gxdFGHNm0ID-y2d5Ur4V82HShS0GdzV0X9smoiT3syxUHLr2naPUJ_RNFyrTM_N_8mqfAbaUOlLyL0ojsjqQKjC0xyDnS5_y6-Xd6ziUiCZ_j0ksCl4wX8DagZyhmYwPIXVdetZ0qHEtjPhxEt4svmaVQgvGWnvjECyhR0HKT4ngb8x3h_ZgM3VIYfSMNF3E4eqnO2zJknLJquWFxXuW4sL-ReX54YSXvnCx8SVqAQ7zojHSyE5fkPEfhyv0iKohBdbl3T9sbsIb6MA0eTcTScwGI4F76SsgQsj4p4S4Lg4Oa17CQHthg&session_id=c1f2c587-91e4-47c2-b00e-d00c8b4377f3&state=4a47840c-9443-47b1-8bbc-57f360ef024b&token_type=Bearer&session_state=dfe6c26f260f33a7390e87e29e0a29caa043b78e0869ebb320c19dbd19bc4e6f.926b7b05-aab3-4861-9004-d0bfe84ba957&expires_in=299
```

Sample for **response_type=token+id_token**
```
-------------------------------------------------------
REQUEST:
-------------------------------------------------------
https://jenkins-build.jans.io/jans-auth/restv1/authorize?response_type=token+id_token&client_id=a9c7fdfb-5a57-4aac-9007-80cbba64e22e&scope=openid+profile+address+email&redirect_uri=https%3A%2F%2Fjenkins-build.jans.io%2Fjans-auth-rp%2Fhome.htm&state=6edcc8f6-90a2-4d31-a210-91b79414a9a3&nonce=c0fa6fd8-ec63-4d24-8e2f-214f0c63c1f8&prompt=&ui_locales=&claims_locales=&acr_values=&request_session_id=false

-------------------------------------------------------
RESPONSE:
-------------------------------------------------------
HTTP/1.1 302 Found
Location: https://jenkins-build.jans.io/jans-auth-rp/home.htm#access_token=4420ad9e-2310-434f-9004-c6071fbc2503&scope=address+openid+profile+email&id_token=eyJraWQiOiJjb25uZWN0XzQwNGU3ZWQ4LTdkNGQtNDAxNi1hNWRkLTUyM2M0NDgxMzZiMl9zaWdfcnMyNTYiLCJ0eXAiOiJqd3QiLCJhbGciOiJSUzI1NiJ9.eyJhdF9oYXNoIjoibWRLd2xrc2RFWElUUUQ1VXMtTmM1ZyIsInN1YiI6IkZHV01DcWZLYlktODRfZGZoUmFtQVE3dGlwYmlqX0pCbVFiejA4UkdGaHMiLCJhbXIiOlsiMTAiXSwiaXNzIjoiaHR0cHM6Ly9qZW5raW5zLWJ1aWxkLmphbnMuaW8iLCJub25jZSI6ImMwZmE2ZmQ4LWVjNjMtNGQyNC04ZTJmLTIxNGYwYzYzYzFmOCIsInNpZCI6ImMyMDQwNDlhLTc2MzgtNDUzNC1iMDhhLTdiYzQ5YmU0OWZiNyIsImphbnNPcGVuSURDb25uZWN0VmVyc2lvbiI6Im9wZW5pZGNvbm5lY3QtMS4wIiwiYXVkIjoiYTljN2ZkZmItNWE1Ny00YWFjLTkwMDctODBjYmJhNjRlMjJlIiwicmFuZG9tIjoiMGJhNzczYjgtNDIwOS00NDczLTk0ZjQtY2IzMGI0MTgxZjMwIiwiYWNyIjoiYmFzaWMiLCJzX2hhc2giOiJiY2c2TC1WeENsVGJXMVJaampHMFRRIiwiYXV0aF90aW1lIjoxNjc2OTE2NTg5LCJleHAiOjE2NzY5MjAxOTEsImdyYW50IjoiaW1wbGljaXQiLCJpYXQiOjE2NzY5MTY1OTF9.nreSCrTYr282i5Oxf2v1xTg5tTGQgC-7DA_bQobkqfRdYRyyZivC1N2Yji9xSXprMNTu03Q1jbpQrf7B-HxCsTWo2QYQhwYFaxe7Rr--IAWWzgMfmPf667ZP0Kv11kKVeO4JcEtwUgo9VKB8MZYt9V32izXWIqcH4ndLIViUyawikWDero_m0K5HiII9DatzY_MWRBwdFk-fitRORo7_4We0z7b_3FZElDoGDjtvtSxnpVAAAWa0cXPrhbSRV7MvhOL4xofNHPcsTjlzxktl_FD2_0OdsydpdPZyLrVwZ-2gMDtrpDEhnFNMFLlSrK9mg_URtzSKBfKWarOaPg1r5Q&session_id=0c55ec01-db6e-4456-ad1d-59b43ed34e51&state=6edcc8f6-90a2-4d31-a210-91b79414a9a3&token_type=Bearer&session_state=35a21d5135b077c4679065cb05996671f49fcdb1cdaf899de8652fe1fbcd137d.ade60b56-b124-4e32-b1ba-697e76494a49&expires_in=299
```

For now I'm closing this ticket. @manojs1978 when you get chance would you please re-test it ? If you will be able to reproduce it please attach AS logs in TRACE log level and request/response, so it's easier for me to catch it.

**Closed by yuriyz** 2023-02-23 12:46 UTC
Labels: comp-jans-auth-server, kind-feature, enhancement
