### ISSUE TITLE
feat: During Setup, generate a key description

### ISSUE THREAD

**Issue by nynymike** [JanssenProject/jans#1790] opened 2022-07-14 00:13 UTC
Having a description of the key would be very helpul. Otherwise the we get a veiw like this:

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/3717101/178858032-0522be98-ddf1-4009-a0d7-bd57a7808208.png">

What is this key used for? We could cross reference the kid with the jwks_uri... but isn't the purpose of the key known at the time of generation?

**Comment by duttarnab** [comment] 2022-07-15 11:43
The issue is fixed after reinstallation of jans-server.

![image](https://user-images.githubusercontent.com/32794267/179216717-06eeacab-7e03-4b19-b4f9-4ed469a0eea6.png)

**Comment by duttarnab** [comment] 2022-07-18 05:17
I found that 2 days after reinstallation the keys `name` and `desc` are missing from jwks_url response. Immediate after reinstallation `name` and `desc` were present. 

![image](https://user-images.githubusercontent.com/32794267/179449195-5b403cd4-02f1-40c3-8ab8-85b9a5bdfe0d.png)

**Comment by duttarnab** [comment] 2022-07-19 05:20
Hi @yuriyz 

The keys are rotated by AS.  

`"keyRegenerationEnabled":true,"keyRegenerationInterval":48`

**Comment by yuriyz** [comment] 2022-08-09 12:29
@duttarnab issue is fixed on AS side. Please check with latest AS.

**Closed** 2022-08-09 12:28 UTC
Labels: kind-feature
