### ISSUE TITLE
fix: fix(jans-auth-server): white/blank screen after device flow authn #4237 -autocreated 

### ISSUE THREAD

**Issue by mo-auto** [JanssenProject/jans#4244] opened 2023-03-20 23:02 UTC
This issue was created because no open issues were referenced in your PR (#4243).

**Comment by yuriyz** [comment] 2023-03-21 10:31
@moabu not clear why bot created this issue. PR has `closes #4237`.

Duplicate of https://github.com/JanssenProject/jans/issues/4237

**Closed by yuriyz** 2023-03-21 10:31 UTC
Labels: kind-bug
