### ISSUE TITLE
fix(jans-config-api): fix agama GET operation endpoint

### ISSUE THREAD

**Issue by moabu** [JanssenProject/jans#2472] opened 2022-09-26 19:42 UTC
**Request:**
GET on `/jans-config-api/api/v1/agama`

**Exception:**
```
2022-09-26 14:19:43.562:WARN :oejs.HttpChannel:qtp762476028-21: /jans-config-api/api/v1/agama
org.jboss.resteasy.spi.UnhandledException: io.jans.orm.exception.EntryPersistenceException: Failed to find entries with key: 'flows', expression: 'null'
	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:105)
	...
	at io.jans.configapi.filters.MetricFilter.doFilter(MetricFilter.java:56)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:210)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
	at io.jans.configapi.filters.CorsFilter.doFilter(CorsFilter.java:64)
	...
Caused by: 
io.jans.orm.exception.EntryPersistenceException: Failed to find entries with key: 'flows', expression: 'null'
	at io.jans.orm.sql.impl.SqlEntryManager.findEntriesImpl(SqlEntryManager.java:500)
	at io.jans.orm.sql.impl.SqlEntryManager.findPagedEntries(SqlEntryManager.java:411)
	at jdk.internal.reflect.GeneratedMethodAccessor951.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38)
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:106)
	at io.jans.orm.PersistenceEntryManager$EntityManager$722412412$Proxy$_$$_WeldClientProxy.findPagedEntries(Unknown Source)
	at io.jans.configapi.service.auth.AgamaFlowService.searchFlows(AgamaFlowService.java:94)
	at io.jans.configapi.service.auth.AgamaFlowService$Proxy$_$$_WeldClientProxy.searchFlows(Unknown Source)
	at io.jans.configapi.rest.resource.auth.AgamaResource.doSearch(AgamaResource.java:412)
	at io.jans.configapi.rest.resource.auth.AgamaResource.getFlows(AgamaResource.java:87)
	at io.jans.configapi.rest.resource.auth.AgamaResource$Proxy$_$$_WeldSubclass.getFlows(Unknown Source)
	at io.jans.configapi.rest.resource.auth.AgamaResource$Proxy$_$$_WeldClientProxy.getFlows(Unknown Source)
```

**Comment:**
Remaining CRUD operations work without any issues.

**Comment by pujavs** [comment] 2022-09-27 16:57
@yuremm, this issue is  in MySql DB wherein the paged result

**Comment by jgomer2001** [comment] 2022-09-29 18:59
@pujavs , the problem is that default sort-by value employed in service implementation is `qname`; here: https://github.com/JanssenProject/jans/blob/main/jans-config-api/server/src/main/java/io/jans/configapi/rest/resource/auth/AgamaResource.java#L74

But the "proper" value should be `agFlowQname`, that is, `Flow.ATTR_NAMES.QNAME`

**Comment by pujavs** [comment] 2022-09-30 05:32
thankyou @yurem and @jgomer2001 for your comments. It's strange though that LDAP search is not throwing error and return 200 response.
I will change to use`agFlowQname`, test and revert.

**Comment by pujavs** [comment] 2022-09-30 10:53
Fixed via PR [2513](https://github.com/JanssenProject/jans/pull/2513)
Testing on MySQL env
![image](https://user-images.githubusercontent.com/43700552/193255001-1b6fcf6e-9f06-4875-94c2-eb9568ae6e12.png)

**Closed** 2022-09-30 11:53 UTC
Labels: kind-bug, comp-jans-config-api
