### ISSUE TITLE
fix: jans-config-api not starting with couchbase backend

### ISSUE THREAD

**Issue by devrimyatar** [JanssenProject/jans#3264] opened 2022-12-08 15:03 UTC
**Describe the bug**
jans-config-api is not starting when couchbase is used as backend.

**To Reproduce**

1. Install jans with couchbase backend (cb-7.1.1)
2. Check logs of jans-config-api

**Additional context**
See jetty log file
[2022_12_08.jetty.log](https://github.com/JanssenProject/jans/files/10186612/2022_12_08.jetty.log)

**Comment by yurem** [comment] 2022-12-13 15:52
In your code:
```
            scope = scopeService.getScope(rsScope.getInum());
...
                scope.setId(rsScope.getName());
...
                scopeService.updateScope(scope);
```

Are you sure that in your json file inum/id are in sync? Why you search by inum and after that override id?

**Comment by pujavs** [comment] 2022-12-14 05:38
These are precautionary code to update scope post creation. 
But do you think this code causes `io.jans.orm.exception.UnsupportedOperationException` issue in CB and not other DB?

**Comment by pujavs** [comment] 2023-01-13 14:53
@yurem, the issue is only there in-case of CB, do you think any change is required in config-api ?

**Comment by yurem** [comment] 2023-01-17 19:04
Root case is here:
```
io.jans.orm.exception.UnsupportedOperationException: There is no attribute with objectClasses in DB! Entry is invalid: 'Scope{dn='inum=1800.01.1,ou=scopes,o=jans', inum='1800.01.1', displayName='Config API scope https://jans.io/oauth/config/acrs.readonly', id='https://jans.io/oauth/config/acrs.readonly', iconUrl='null', description='Config API scopes scope https://jans.io/oauth/config/acrs.readonly', scopeType=oauth, claims=null, defaultScope=false, groupClaims=null, dynamicScopeScripts=null, umaAuthorizationPolicies=null, creatorId=null, creatorType=null, creationDate=Thu Dec 08 14:59:04 UTC 2022, creatorAttributes={}, deletable=null, expirationDate=null, attributes=ScopeAttributes{spontaneousClientScopes=[], showInConfigurationEndpoint=false}}'
```

**Comment by pujavs** [comment] 2023-01-25 17:28
Fixed via PR [3697](https://github.com/JanssenProject/jans/pull/3697)

**Closed** 2023-01-25 17:46 UTC
Labels: kind-bug, comp-jans-config-api
