### ISSUE TITLE
fix(jans): getting error while enabling duo script

### ISSUE THREAD

**Issue by manojs1978** [JanssenProject/jans#5313] opened 2023-06-22 07:52 UTC
**Describe the bug**
getting error while enabling duo script

**To Reproduce**
install jans 1.0.15.nightly
enable duo script
See error in log

**Expected behavior**
duo script should enable

**Screenshots**

**Desktop (please complete the following information):**
  - OS: suse
  - Version 15 sp4
  - DB mysql
  - jans 1.0.15.nightly

**Smartphone (please complete the following information):**

**Additional context**

```
io.jans.exception.PythonException: Failed to load python file 'java.io.ByteArrayInputStream@7a51db71' at io.jans.service.PythonService.loadPythonScript(PythonService.java:187) at io.jans.service.PythonService$Proxy$_$$_WeldClientProxy.loadPythonScript(Unknown Source) at io.jans.service.custom.script.ExternalTypeCreator.createExternalTypeFromStringWithPythonException(ExternalTypeCreator.java:150) at io.jans.service.custom.script.ExternalTypeCreator.createExternalType(ExternalTypeCreator.java:77) at io.jans.service.custom.script.ExternalTypeCreator$Proxy$_$$_WeldClientProxy.createExternalType(Unknown Source) at io.jans.service.custom.script.CustomScriptManager.reloadCustomScriptConfigurations(CustomScriptManager.java:276) at io.jans.service.custom.script.CustomScriptManager.reloadImpl(CustomScriptManager.java:173) at io.jans.service.custom.script.CustomScriptManager.reload(CustomScriptManager.java:143) at io.jans.service.custom.script.CustomScriptManager.reloadTimerEvent(CustomScriptManager.java:118) at io.jans.service.custom.script.CustomScriptManager$Proxy$_$$_WeldSubclass.reloadTimerEvent(Unknown Source) at jdk.internal.reflect.GeneratedMethodAccessor136.invoke(Unknown Source) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:566) at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95) at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:85) at org.jboss.weld.injection.MethodInvocationStrategy$SimpleMethodInvocationStrategy.invoke(MethodInvocationStrategy.java:168) at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:330) at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:308) at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286) at jakarta.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:125) at org.jboss.weld.util.Observers.notify(Observers.java:166) at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285) at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273) at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:177) at org.jboss.weld.event.ObserverNotifier.fireEvent(ObserverNotifier.java:159) at org.jboss.weld.manager.BeanManagerImpl.fireEvent(BeanManagerImpl.java:632) at org.jboss.weld.util.ForwardingBeanManager.fireEvent(ForwardingBeanManager.java:104) at io.jans.service.timer.TimerJob.execute(TimerJob.java:45) at io.jans.service.timer.JobExecutionDelegate.execute(JobExecutionDelegate.java:37) at org.quartz.core.JobRunShell.run(JobRunShell.java:202) at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573) Caused by: File "duo.py", line 105 try: ^ SyntaxError: mismatched input '' expecting DEDENT at org.python.core.ParserFacade.fixParseError(ParserFacade.java:95) at org.python.core.ParserFacade.parse(ParserFacade.java:190) at org.python.core.Py.compile_flags(Py.java:2249) at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:297) at io.jans.service.PythonService.loadPythonScript(PythonService.java:184) ... 30 more ==================Further details============================ Failed to load python file 'java.io.ByteArrayInputStream@7a51db71'
```

**Comment by jgomer2001** [comment] 2023-07-26 21:36
Duplicate of #4710

**Closed by jgomer2001** 2023-07-26 21:36 UTC
Labels: kind-bug
